# Generated by Django 2.2.6 on 2019-10-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(null=True)),
                ('locked', models.SmallIntegerField()),
                ('password', models.CharField(max_length=255)),
                ('password_requested_at', models.DateTimeField(null=True)),
                ('roles', models.TextField()),
                ('salt', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('username_canonical', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fos_user',
                'managed': True,
            },
        ),
    ]
