# Generated by Django 2.2.6 on 2019-10-30 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = []
