# Generated by Django 2.2.6 on 2019-11-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_django_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingprovider',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hostingprovider',
            name='iconurl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hostingprovider',
            name='partner',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Partner', 'Partner'), ('Dev Partner', 'Dev Partner'), ('Certified Gold Partner', 'Certified Gold Partner'), ('Gold Partner', 'Gold Partner')], default='', max_length=255, null=True),
        ),
    ]
