# Generated by Django 2.2.6 on 2019-10-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # TODO Possibly clean up these later
    dependencies = [
        ('accounts', '0002_add_django_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='model',
            field=models.CharField(choices=[('groeneenergie', 'green energy'), ('compensatie', 'compensation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='showonwebsite',
            field=models.BooleanField(verbose_name='Show on website'),
        ),
        migrations.AlterField(
            model_name='datacentercertificate',
            name='datacenter',
            field=models.ForeignKey(db_column='id_dc', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datacenter_certificates', to='accounts.Datacenter'),
        ),
        migrations.AlterField(
            model_name='datacenterclassification',
            name='datacenter',
            field=models.ForeignKey(db_column='id_dc', on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='accounts.Datacenter'),
        ),
        migrations.AlterField(
            model_name='hostingprovider',
            name='datacenter',
            field=models.ManyToManyField(related_name='hostingproviders', through='accounts.HostingproviderDatacenter', to='accounts.Datacenter'),
        ),
        migrations.AlterField(
            model_name='hostingprovider',
            name='showonwebsite',
            field=models.BooleanField(verbose_name='Show on website'),
        ),
        migrations.AlterField(
            model_name='hostingprovidercertificate',
            name='hostingprovider',
            field=models.ForeignKey(db_column='id_hp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_certificates', to='accounts.Datacenter'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='fos_user_usernam_5d00b4_idx'),
        ),
    ]
