# Generated by Django 2.2.7 on 2019-11-14 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("accounts", "0005_default_fields_for_hostingprovider"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostingCommunication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("template", models.CharField(max_length=128)),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="hostingcommunication",
            name="hostingprovider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.Hostingprovider",
            ),
        ),
    ]
