# Generated by Django 2.2.13 on 2020-06-03 11:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200206_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='model',
            field=models.CharField(choices=[('groeneenergie', 'green energy'), ('compensatie', 'compensation'), ('mixed', 'mixed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hostingprovider',
            name='model',
            field=django_mysql.models.EnumField(choices=[('groeneenergie', 'green energy'), ('compensatie', 'compensation'), ('mixed', 'mixed')], default='compensatie'),
        ),
    ]
