# Generated by Django 2.2.17 on 2021-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_date_joined_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="legacy_password",
            field=models.CharField(
                db_column="password",
                default="",
                max_length=128,
                verbose_name="legacy_password",
            ),
        ),
    ]
