# Generated by Django 2.2.19 on 2021-03-14 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_datacentresupportingdocument_hostingprovidersupportingdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacentresupportingdocument',
            options={'verbose_name': 'Supporting Document'},
        ),
        migrations.AlterModelOptions(
            name='hostingprovidersupportingdocument',
            options={'verbose_name': 'Supporting Document'},
        ),
        migrations.AddField(
            model_name='datacentresupportingdocument',
            name='public',
            field=models.BooleanField(default=True, help_text="If this is checked, we'll add a link to this document/page in your entry in the green web directory."),
        ),
        migrations.AddField(
            model_name='datacentresupportingdocument',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AddField(
            model_name='hostingprovidersupportingdocument',
            name='public',
            field=models.BooleanField(default=True, help_text="If this is checked, we'll add a link to this document/page in your entry in the green web directory."),
        ),
        migrations.AddField(
            model_name='hostingprovidersupportingdocument',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name='datacentresupportingdocument',
            name='url',
            field=models.URLField(blank=True, help_text="Alternatively, if you add a link, we'll fetch a copy, to show when it was accessed."),
        ),
        migrations.AlterField(
            model_name='hostingprovidersupportingdocument',
            name='url',
            field=models.URLField(blank=True, help_text="Alternatively, if you add a link, we'll fetch a copy, to show when it was accessed."),
        ),
    ]
