# Generated by Django 2.2.19 on 2021-04-15 13:14

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("accounts", "0014_auto_20210314_2305"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCenterLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                (
                    "datacenter",
                    models.ForeignKey(
                        db_column="id_dc",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.Datacenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datacentre Location",
                "db_table": "datacenters_locations",
            },
        ),
    ]
