# Generated by Django 3.2 on 2021-06-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210424_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatacentreSupportingDocument',
            new_name='DatacenterSupportingDocument',
        ),
    ]
