# Generated by Django 3.2 on 2021-09-15 16:02

from django.db import migrations


def add_template_messages(apps, schema_editor):

    SupportMessage = apps.get_model("accounts", "SupportMessage")

    # create our pending removal message
    pending_removal, created = SupportMessage.objects.get_or_create(
        category="pending-removal"
    )
    pending_removal.subject = "Pending removal from the Green Web Directory due to questions around the green hosting of {{host.name}}"

    pending_removal.body = """
## Dear hoster,

{% if recipient.date_joined %}On {{ recipient.date_joined }}{% else %}Some time in the past{% endif %} you registered {{ host.name }} at the [Green Web Directory][1].

A recent check discovered that your website (https://{{ host.website }} no longer turns up as green when checked against the green credentials available in our system for your company.

For now, we have placed {{ host.name }} on the list of green hosters that need to update their ASN or ip-ranges in the [admin system][2]. After approval, the website will be visible in the Green Web Directory again.

Thanks for your help in keeping the Green Web Directory up-to-date! We’re experiencing significant growth in the number of checks against the database, currently over 7 million per day and counting, so it does make sense!

With best regards,
Green Web Foundation Support Team

[1]: https://www.thegreenwebfoundation.org
[2]: https://admin.thegreenwebfoundation.org
"""
    pending_removal.save()

    need_more_info, created = SupportMessage.objects.get_or_create(
        category="need-more-info"
    )
    need_more_info.subject = "Additional information needed to approve your listing in the Green Web Directory"
    need_more_info.body = """
Dear hoster,

{% if user.date_joined %}On {{ user.date_joined }}{% else %}Some time in the past{% endif %} you registered {{ host.name }} at the Green Web Directory [1]. Since it is not directly clear to us why and how you are green hosted, we kindly ask you to provide us with the following additional information:

Could you refer us to your corporate social responsibility page, or a comparable page where you explain how you have approached to become a green hoster or website?

Is it possible to refer us to a valid certificate awarded to yourself or the company that provides your digital infrastructure to you?

Thanks for your help in keeping the Green Web Directory up-to-date! We’re experiencing significant growth in the number of checks against the database, currently over 7 million per day and counting, so it does make sense!

With best regards,
Green Web Foundation Support Team

[1] https://www.thegreenwebfoundation.org/

    """
    need_more_info.save()


def remove_template_messages(apps, schema_editor):
    """
    Removes the two message templates used for
    sending support messages
    """
    SupportMessage = apps.get_model("accounts", "SupportMessage")
    SupportMessage.objects.filter(category="need-more-info").delete()
    SupportMessage.objects.filter(category="pending-removal").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_hostingcommunication_message_content"),
    ]

    operations = [migrations.RunPython(add_template_messages, remove_template_messages)]
