# Generated by Django 3.2 on 2021-09-17 10:12

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_template_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingprovider',
            name='staff_labels',
            field=taggit.managers.TaggableManager(blank=True, help_text='Labels to apply to providers to make it easier to flag for follow up by staff or other categorisation to support internal admin. Internally facing.', related_name='labels', through='accounts.ProviderLabel', to='accounts.Label', verbose_name='Staff labels'),
        ),
        migrations.AlterField(
            model_name='providerlabel',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hostingprovider'),
        ),
    ]
