# Generated by Django 3.2.16 on 2022-12-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_refactor_providerrequest_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrequestevidence",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
