# Generated by Django 3.2.16 on 2023-01-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_provider_request_evidence_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrequest",
            name="authorised_by_org",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
