# Generated by Django 3.2.16 on 2023-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0039_hostingprovider_city'), ('accounts', '0040_auto_20230124_1123'), ('accounts', '0041_remove_providerrequestlocation_description')]

    dependencies = [
        ('accounts', '0038_provider_request_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingprovider',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='providerrequestlocation',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
