# Generated by Django 3.2.16 on 2023-01-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_hostingprovider_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrequestlocation',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='providerrequestlocation',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
