# Generated by Django 3.2.16 on 2023-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_hostingprovider_city_squashed_0041_remove_providerrequestlocation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerrequest',
            name='missing_network_explanation',
            field=models.TextField(blank=True, help_text='If an organisation is not listing the IP Ranges and AS numbers we need to be able to explain why to list them as green.', verbose_name='Reason for no IP / AS data'),
        ),
    ]
