# Generated by Django 3.2.18 on 2023-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0046_providersharedsecret"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
