# Generated by Django 3.2.18 on 2023-04-25 13:16

from django.db import migrations
from ..group_permissions import (
    group_permissions_2023_04_26_disallow_adding_hp_and_dc,
    group_permissions_2023_04_26_revert_disallow_adding_hp_and_dc,
)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0047_provider_request_approved_date"),
    ]

    operations = [
        # explicitly set group permissions
        migrations.RunPython(
            code=group_permissions_2023_04_26_disallow_adding_hp_and_dc,
            reverse_code=group_permissions_2023_04_26_revert_disallow_adding_hp_and_dc,
        ),
    ]
