# Generated by Django 3.2.18 on 2023-05-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_disallow_adding_hp_and_dc'),
        ('accounts', '0051_auto_20230508_1317'),
    ]

    operations = [
    ]
