# Generated by Django 3.2.19 on 2023-05-30 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_hostingprovider_created_by(apps, schema_editor):
    """
    Assign Hostingprovider.created_by based on User.hostingprovider values for existing objects
    """
    db_alias = schema_editor.connection.alias

    User = apps.get_model(settings.AUTH_USER_MODEL)

    for user in (
        User.objects.using(db_alias).filter(hostingprovider__isnull=False).iterator()
    ):
        user.hostingprovider.created_by = user
        user.hostingprovider.save()


class Migration(migrations.Migration):
    """
    - Rename Datacenter.user to Datacenter.created_by
    - Change Datacenter.created_by to allow null values
        and set a related_name to avoid clash with User.hostingprovider
    - Add field Hostingprovider.created_by and populate its value based on existing User records
    """

    dependencies = [
        ("accounts", "0054_provider_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datacenter", old_name="user", new_name="created_by"
        ),
        migrations.AlterField(
            model_name="datacenter",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hostingprovider",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hostingproviders_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            code=populate_hostingprovider_created_by, reverse_code=lambda *args: ...
        ),
    ]
