# Generated by Django 3.2.19 on 2023-05-31 12:38

from django.db import migrations
from guardian.models import Group
from guardian.shortcuts import assign_perm, remove_perm
from .. import permissions


def set_admin_global_perms(apps, schema_editor):
    """
    Assign global permissions (for all Hostingprovider and Datacenter objects)
    for all members of the "admin" group.
    """
    db_alias = schema_editor.connection.alias

    admin_group = Group.objects.using(db_alias).filter(name="admin").get()
    assign_perm(str(permissions.manage_datacenter), admin_group)
    assign_perm(str(permissions.manage_provider), admin_group)


def remove_admin_global_perms(apps, schema_editor):
    """
    Remove global permissions (for all Hostingprovider and Datacenter objects)
    from all members of the "admin" group.
    """
    db_alias = schema_editor.connection.alias

    admin_group = Group.objects.using(db_alias).filter(name="admin").get()
    remove_perm(str(permissions.manage_datacenter), admin_group)
    remove_perm(str(permissions.manage_provider), admin_group)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0054_hostingprovider_datacenter_created_by"),
    ]

    operations = [
        migrations.RunPython(
            code=set_admin_global_perms, reverse_code=remove_admin_global_perms
        ),
    ]
