# Generated by Django 3.2.19 on 2023-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0057_remove_user_hostingprovider_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Django way of designating if the user can log into the admin. This flag is ignored in GWF Admin",
                verbose_name="staff status",
            ),
        ),
    ]
