# Generated by Django 3.2.20 on 2023-09-06 12:09

from django.db import migrations, models


def populate_pr_consent(apps, schema_editor):
    """
    Integrate ProviderRequestConsent objects into ProviderRequest
    after it was extended with new fields
    """
    db_alias = schema_editor.connection.alias
    ProviderRequestConsent = apps.get_model("accounts", "ProviderRequestConsent")
    for consent in ProviderRequestConsent.objects.using(db_alias).all():
        pr = consent.request
        pr.data_processing_opt_in = consent.data_processing_opt_in
        pr.newsletter_opt_in = consent.newsletter_opt_in
        pr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0059_merge_20230712_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrequest",
            name="data_processing_opt_in",
            field=models.BooleanField(
                default=False, verbose_name="Data processing consent"
            ),
        ),
        migrations.AddField(
            model_name="providerrequest",
            name="newsletter_opt_in",
            field=models.BooleanField(default=False, verbose_name="Newsletter signup"),
        ),
        migrations.RunPython(code=populate_pr_consent, reverse_code=lambda *args: ...),
        migrations.DeleteModel(
            name="ProviderRequestConsent",
        ),
    ]
