# Generated by Django 3.2.20 on 2023-09-06 19:10

from django.db import migrations, models


def rename_status(apps, schema_editor):
    """
    Rename status OPEN to MORE INFO REQUIRED for existing ProviderRequest objects
    """
    db_alias = schema_editor.connection.alias
    ProviderRequest = apps.get_model("accounts", "ProviderRequest")
    ProviderRequest.objects.using(db_alias).filter(status="Open").update(
        status="More info required"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0060_provider_request_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending review", "Pending Review"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("More info required", "Open"),
                    ("Removed", "Removed"),
                ],
                max_length=255,
            ),
        ),
        migrations.RunPython(code=rename_status, reverse_code=lambda *args: ...),
    ]
