# Generated by Django 5.0.9 on 2025-05-09 15:55

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):

    def populate_verification_bases(apps, schema_editor):
        VerificationBasis = apps.get_model("accounts", "VerificationBasis")
        bases = [
                "We use 100% green energy from our own infrastructure.",
                "We operate in a region that has a grid intensity of less than 20g CO2e/kWh or uses over 99% renewable power.",
                "We directly pay for green energy to cover the non-green energy we use.",
                "We purchase quality carbon offsets to cover the non-green energy we use.",
                "We resell or actively use a provider that is already in the Green Web Dataset.",
        ]
        for base in bases:
            VerificationBasis.objects.create(name=base, slug=slugify(base))

    dependencies = [
        ("accounts", "0066_hostingprovider_carbon_txt_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basis for verification",
                "verbose_name_plural": "Bases for verification",
            },
        ),
        migrations.RunPython(populate_verification_bases),
        migrations.CreateModel(
            name="ProviderRequestVerificationBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.providerrequest",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="accounts.verificationbasis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="providerrequest",
            name="verification_bases",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="accounts.ProviderRequestVerificationBasis",
                to="accounts.VerificationBasis",
                verbose_name="Basis for verification",
            ),
        ),
    ]
