# Generated by Django 5.0.9 on 2025-05-12 04:13

from django.db import migrations
from ..group_permissions import group_permissions_2025_05_12_add_verification_basis_permissions_for_admins

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0067_verificationbasis_and_more"),
    ]

    operations = [
        migrations.RunPython(
            group_permissions_2025_05_12_add_verification_basis_permissions_for_admins
        )
    ]
