# Generated by Django 5.0.9 on 2025-05-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0068_verification_basis_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationbasis",
            name="required_evidence_link",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Required evidence link",
            ),
        ),
    ]
