# Generated by Django 5.0.9 on 2025-05-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0069_verificationbasis_required_evidence_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderVerificationBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.hostingprovider",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="accounts.verificationbasis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
