# Generated by Django 5.0.9 on 2025-05-30 06:41

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0072_add_state_to_linkedomains"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkeddomain",
            name="primary",
            field=models.BooleanField(
                default=False,
                verbose_name="This domain represents this hosting provider itself.",
            ),
        ),
    ]
