# Generated by Django 5.0.9 on 2025-06-05 12:11

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0077_add_active_flag_to_linkeddomain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="linkeddomain",
            old_name="primary",
            new_name="is_primary",
        ),
    ]
