# Generated by Django 5.0.9 on 2025-06-23 06:46

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0078_alter_linkeddomain_rename_primary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkeddomain",
            options={"verbose_name_plural": "Linked Domains"},
        ),
        migrations.AddField(
            model_name="hostingprovider",
            name="verification_bases",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="accounts.ProviderVerificationBasis",
                to="accounts.VerificationBasis",
                verbose_name="Basis for verification",
            ),
        ),
        migrations.AlterField(
            model_name="datacentersupportingdocument",
            name="archived",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="If this is checked, this document will not show up in any queries. Should not be editable via the admin interface by non-staff users.",
            ),
        ),
        migrations.AlterField(
            model_name="hostingprovidersupportingdocument",
            name="archived",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="If this is checked, this document will not show up in any queries. Should not be editable via the admin interface by non-staff users.",
            ),
        ),
        migrations.AlterField(
            model_name="providerlabel",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="accounts.label",
            ),
        ),
        migrations.AlterField(
            model_name="providerrequestservice",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="accounts.service",
            ),
        ),
        migrations.AlterField(
            model_name="providerservice",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="accounts.service",
            ),
        ),
    ]
