# Generated by Django 5.0.9 on 2025-07-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0079_alter_linkeddomain_options_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hostingprovider",
            name="hp_showonwebsite",
        ),
        migrations.RenameField(
            model_name="hostingprovider",
            old_name="showonwebsite",
            new_name="is_listed",
        ),
        migrations.AddIndex(
            model_name="hostingprovider",
            index=models.Index(
                fields=["is_listed"], name="hp_is_listed"
            ),
        ),
    ]
