# Generated by Django 5.0.9 on 2025-07-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0081_rename_datacenter_showonwebsite_to_is_listed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacenter",
            name="is_listed",
            field=models.BooleanField(
                default=False,
                verbose_name="List this datacenter in the greenweb directory?",
            ),
        ),
    ]
