# Generated by Django 5.0.9 on 2025-08-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0083_carbontxtmotivation_providercarbontxt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providercarbontxtmotivation",
            name="description",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
