# Generated by Django 5.0.9 on 2025-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0084_providercarbontxtmotivation_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providercarbontxt",
            name="carbon_txt_url",
            field=models.URLField(max_length=512, null=True, unique=True),
        ),
    ]
