# Generated by Django 5.0.9 on 2025-09-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0087_rename_carbon_txt_id_carbontxtdomainresultcache_carbon_txt"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="carbontxtdomainresultcache",
            index=models.Index(fields=["domain"], name="accounts_ca_domain_29aab9_idx"),
        ),
        migrations.AddIndex(
            model_name="carbontxtdomainresultcache",
            index=models.Index(
                fields=["created"], name="accounts_ca_created_458ba0_idx"
            ),
        ),
    ]
