# Generated by Django 5.0.9 on 2025-09-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0088_carbontxtdomainresultcache_accounts_ca_domain_29aab9_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="LinkedDomain",
        ),
    ]
