# Generated by Django 5.2.9 on 2025-12-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0089_delete_linkeddomains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostingprovider",
            name="datacenter",
            field=models.ManyToManyField(
                related_name="hostingproviders",
                through="accounts.HostingproviderDatacenter",
                through_fields=("hostingprovider", "datacenter"),
                to="accounts.datacenter",
            ),
        ),
    ]
