# Generated by Django 5.2.9 on 2026-01-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0090_alter_hostingprovider_datacenter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providercarbontxt",
            name="carbon_txt_url",
            field=models.URLField(max_length=255, null=True, unique=True),
        ),
    ]
