# Generated by Django 5.2.9 on 2026-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0091_alter_providercarbontxt_carbon_txt_url"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hostingprovider",
            index=models.Index(
                fields=["archived", "is_listed", "country"],
                name="hp_directory_by_country",
            ),
        ),
    ]
