# Generated by Django 5.2.9 on 2026-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0092_hostingprovider_hp_directory_by_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostingprovider",
            name="linked_providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other active verified providers this provider relies on for its green status.",
                related_name="linked_by_providers",
                to="accounts.hostingprovider",
                verbose_name="Upstream linked providers",
            ),
        ),
        migrations.AddField(
            model_name="providerrequest",
            name="linked_providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Active verified providers this request relies on for its green status.",
                related_name="provider_requests_linked",
                to="accounts.hostingprovider",
                verbose_name="Upstream linked providers",
            ),
        ),
    ]
