# Generated by Django 5.2.9 on 2026-06-09 06:46

from django.db import migrations, models

def create_default_service(apps, _schema_editor):
    APIService = apps.get_model('accounts', 'APIService')
    APIService.objects.create(name='Carbon.txt API', key="carbon_txt")

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0097_rename_linked_providers_to_upstream_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="api_access_motivation",
        ),
        migrations.AddField(
            model_name="apikey",
            name="motivation",
            field=models.TextField(
                default="[Key created before we added per-key motivation text]"
             ),
            preserve_default=False,
        ),
        migrations.RunPython(
            create_default_service, migrations.RunPython.noop
        )
    ]
