# Generated by Django 5.2.9 on 2026-06-09 13:45

import django.db.models.deletion
from django.db import migrations, models


def populate_default_services(apps, _schema_editor):
        APIService = apps.get_model("accounts", "APIService")
        APIKey = apps.get_model('accounts', 'APIKey')
        service = APIService.objects.filter(key="carbon_txt").first()
        APIKey.objects.filter(service=None).update(service_id=service.pk)

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0098_apiservice_remove_user_api_access_motivation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.apiservice",
            ),
        ),
        migrations.RunPython(
            populate_default_services,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='service',
            field=models.ForeignKey(
                null=False,
                to='accounts.apiservice',
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
    ]
