# Generated by Django 5.2.9 on 2026-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0100_apiservice_documentation_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiservice",
            name="api_url",
            field=models.URLField(default="https://api.greenweb.org"),
            preserve_default=False,
        ),
    ]
