# Generated by Django 5.2.9 on 2026-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0101_apiservice_api_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikeyprivilegelevel",
            name="note",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
