# Generated by Django 5.2.9 on 2026-06-29 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0105_seed_october_2026_verification_bases"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacentersupportingdocument",
            name="claim_coverage_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What percentage of your claims are met by this disclosure? Optional.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="datacentersupportingdocument",
            name="fossil_free_energy_matching",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Annually matched", "Annually matched fossil-free energy"),
                    ("Hourly matched", "Hourly matched fossil-free energy"),
                ],
                help_text="Does this evidence support a claim of using annual matched or hourly matched fossil-free energy?",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hostingprovidersupportingdocument",
            name="claim_coverage_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What percentage of your claims are met by this disclosure? Optional.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="hostingprovidersupportingdocument",
            name="fossil_free_energy_matching",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Annually matched", "Annually matched fossil-free energy"),
                    ("Hourly matched", "Hourly matched fossil-free energy"),
                ],
                help_text="Does this evidence support a claim of using annual matched or hourly matched fossil-free energy?",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providerrequestevidence",
            name="claim_coverage_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="What percentage of your claims are met by this disclosure? Optional.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="providerrequestevidence",
            name="fossil_free_energy_matching",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Annually matched", "Annually matched fossil-free energy"),
                    ("Hourly matched", "Hourly matched fossil-free energy"),
                ],
                help_text="Does this evidence support a claim of using annual matched or hourly matched fossil-free energy?",
                max_length=64,
                null=True,
            ),
        ),
    ]
