# Generated by Django 5.2.9 on 2026-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0106_datacentersupportingdocument_claim_coverage_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hostingprovider",
            name="public_2030_target_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="providerrequest",
            name="public_2030_target_url",
            field=models.URLField(
                blank=True,
                help_text="If your organisation has publicly committed to running on 100% fossil-free power on an hourly basis by 2030, link to your public statement. Optional.",
                max_length=500,
                null=True,
                verbose_name="Public 2030 target for running on fossil-free power",
            ),
        ),
    ]
