# Generated by Django 5.2.9 on 2026-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0106_datacentersupportingdocument_claim_coverage_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacentersupportingdocument",
            name="fossil_free_energy_matching",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Annually matched", "Annually matched fossil-free energy"),
                    ("Hourly matched", "Hourly matched fossil-free energy"),
                ],
                default="Annually matched",
                help_text="Does this evidence support a claim of using annual matched or hourly matched fossil-free energy?",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hostingprovidersupportingdocument",
            name="fossil_free_energy_matching",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Annually matched", "Annually matched fossil-free energy"),
                    ("Hourly matched", "Hourly matched fossil-free energy"),
                ],
                default="Annually matched",
                help_text="Does this evidence support a claim of using annual matched or hourly matched fossil-free energy?",
                max_length=64,
                null=True,
            ),
        ),
    ]
