# Generated by Django 5.2.9 on 2026-07-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0107_alter_datacentersupportingdocument_fossil_free_energy_matching_and_more",
        ),
        ("accounts", "0107_hostingprovider_public_2030_target_url_and_more"),
    ]

    operations = []
