# Generated by Django 2.2.13 on 2020-06-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0003_timestamped_ranges_approvals"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="greencheckasnapprove",
            options={"verbose_name": "Greencheck ASN Submissions"},
        ),
        migrations.AlterModelOptions(
            name="greencheckipapprove",
            options={"verbose_name": "Greencheck IP Range Submission"},
        ),
    ]
