# Generated by Django 2.2.17 on 2021-01-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0005_auto_20200604_1037"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='GreenDomain',
        #     fields=[
        #         (
        #             'id',
        #             models.AutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name='ID'
        #             ),
        #         ),
        #         ('url', models.CharField(max_length=255)),
        #         ('hosted_by', models.CharField(max_length=255)),
        #         ('hosted_by_website', models.CharField(max_length=255)),
        #         ('partner', models.CharField(max_length=255)),
        #         ('green', models.BooleanField()),
        #         ('hosted_by_id', models.IntegerField()),
        #         ('modified', models.DateTimeField()),
        #     ],
        #     options={
        #         'db_table': 'green_presenting',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='TopUrl',
        #     fields=[
        #         (
        #             'id',
        #             models.AutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name='ID',
        #             )
        #         ),
        #         ('url', models.CharField(max_length=255)),
        #     ],
        #     options={
        #         'db_table': 'top_1m_urls',
        #     },
        # ),
        # migrations.RemoveIndex(
        #     model_name='greencheckipapprove',
        #     name='greencheck__created_23c8a1_idx',
        # ),
        migrations.AlterField(
            model_name="greencheck",
            name="greencheck_ip",
            field=models.ForeignKey(
                blank=True,
                db_column="id_greencheck",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="greencheck.GreencheckIp",
            ),
        ),
        # migrations.AlterModelTable(
        #     name='greencheck',
        #     table='greencheck_2020',
        # ),
    ]
