# Generated by Django 3.2 on 2021-04-24 16:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0015_auto_20210320_1728"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="greencheckasn", name="active",),
        migrations.RemoveIndex(model_name="greencheckasn", name="asn",),
        migrations.RemoveIndex(model_name="greencheckstats", name="checked_through",),
        migrations.RemoveIndex(
            model_name="greencheckstatstotal", name="checked_through",
        ),
        migrations.AlterField(
            model_name="greencheckasnapprove",
            name="action",
            field=models.TextField(
                choices=[("empty", "empty"), ("new", "new"), ("update", "update")]
            ),
        ),
        migrations.AlterField(
            model_name="greencheckasnapprove",
            name="status",
            field=models.TextField(
                choices=[
                    ("approved", "Approved"),
                    ("deleted", "Deleted"),
                    ("new", "New"),
                    ("removed", "Removed"),
                    ("update", "Update"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="greencheckipapprove",
            name="action",
            field=models.TextField(
                choices=[("empty", "empty"), ("new", "new"), ("update", "update")]
            ),
        ),
        migrations.AlterField(
            model_name="greencheckipapprove",
            name="status",
            field=models.TextField(
                choices=[
                    ("approved", "Approved"),
                    ("deleted", "Deleted"),
                    ("new", "New"),
                    ("removed", "Removed"),
                    ("update", "Update"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="greenlist",
            name="type",
            field=django_mysql.models.EnumField(
                choices=[
                    ("as", "as"),
                    ("ip", "ip"),
                    ("none", "none"),
                    ("url", "url"),
                    ("whois", "whois"),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="greencheckasn",
            index=models.Index(fields=["active"], name="as_active"),
        ),
        migrations.AddIndex(
            model_name="greencheckasn",
            index=models.Index(fields=["asn"], name="as_asn"),
        ),
        migrations.AddIndex(
            model_name="greencheckstats",
            index=models.Index(
                fields=["checked_through"], name="stats_checked_through"
            ),
        ),
        migrations.AddIndex(
            model_name="greencheckstatstotal",
            index=models.Index(
                fields=["checked_through"], name="stats_total_checked_through"
            ),
        ),
    ]
