# Generated by Django 3.2 on 2021-09-17 10:12

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0017_create_dailystat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greencheck",
            name="type",
            field=django_mysql.models.EnumField(
                choices=[
                    ("as", "as"),
                    ("ip", "ip"),
                    ("none", "none"),
                    ("url", "url"),
                    ("whois", "whois"),
                    ("carbontxt", "carbon.txt"),
                ],
                default="none",
            ),
        ),
    ]
