# Generated by Django 3.2.24 on 2024-02-23 21:22
# FAKE MIGRATION -
# This is needed for tests to pass
# after we switched the main greencheck table from
# greencheck_2021 to greencheck
# in prod, run this as a fake migration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0019_auto_20220515_1835"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="greencheck",
            table="greencheck",
        ),
    ]
