# Generated by Django 5.0.9 on 2025-06-23 06:44

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0021_add_created_to_greendomains"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyStat",
        ),
        migrations.DeleteModel(
            name="GreencheckStats",
        ),
        migrations.DeleteModel(
            name="GreencheckStatsTotal",
        ),
        migrations.DeleteModel(
            name="GreencheckWeeklyStats",
        ),
        migrations.AlterField(
            model_name="co2intensity",
            name="carbon_intensity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="greencheck",
            name="green",
            field=django_mysql.models.EnumField(
                choices=[("yes", "Yes"), ("no", "No"), ("old", "Old")]
            ),
        ),
        migrations.AlterField(
            model_name="greencheck",
            name="type",
            field=django_mysql.models.EnumField(
                choices=[
                    ("url", "url"),
                    ("whois", "whois"),
                    ("ip", "ip"),
                    ("none", "none"),
                    ("as", "as"),
                    ("carbontxt", "carbon.txt"),
                ],
                default="none",
            ),
        ),
        migrations.AlterField(
            model_name="greencheckasnapprove",
            name="action",
            field=models.TextField(
                choices=[
                    ("empty", "empty"),
                    ("new", "new"),
                    ("update", "update"),
                    ("none", "none"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="greencheckipapprove",
            name="action",
            field=models.TextField(
                choices=[
                    ("empty", "empty"),
                    ("new", "new"),
                    ("update", "update"),
                    ("none", "none"),
                ]
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="greenlist",
                    name="type",
                    field=django_mysql.models.EnumField(
                        choices=[
                            ("empty", "empty"),
                            ("new", "new"),
                            ("update", "update"),
                            ("none", "none"),
                        ]
                    ),
                ),
            ]
        )
    ]
