# Generated by Django 5.0.9 on 2025-08-12 09:32

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0023_greendomain_listed_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="greendomain",
            name="type",
            field=django_mysql.models.EnumField(
                choices=[
                    ("url", "url"),
                    ("whois", "whois"),
                    ("ip", "ip"),
                    ("none", "none"),
                    ("as", "as"),
                    ("carbontxt", "carbon.txt"),
                ],
                default="none",
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE greendomain SET type = 'none'
            """
        ),
    ]
