# Generated by Django 5.0.9 on 2025-10-24 14:34

import apps.accounts.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0024_greendomain_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreenDomainBadge",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[apps.accounts.validators.DomainNameValidator],
                    ),
                ),
                ("path", models.URLField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
