# Generated by Django 5.0.9 on 2025-11-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0025_greendomainbadge"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="GreencheckLinked",
                )
            ]
        )
    ]
