# Generated by Django 5.0.9 on 2025-11-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0026_delete_greenchecklinked"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="GreenList",
                )
            ]
        )
    ]
