# Generated by Django 5.0.9 on 2025-11-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0027_delete_greenlist"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="GreencheckTLD",
                )
            ]
        )
    ]
