# This is a reusable composite action which handles everything needed to get a local test environment
# set up in CI. It requires the `python-version` matrix to be set up in the calling workflow.
# It is called from both the deployment and testing workflows, as both need a locally configured
# application.

name: 'Setup environment'
description: 'Set up a test environment for the GWF admin portal'
inputs:
  python-version:
    description: 'Version of python to install'
    required: false
    default: '3.12'
runs:
  using: "composite"
  steps:
      - name: Eco CI Energy Estimation - Get Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v5
        with:
          task: get-measurement
          label: "checkout"
        continue-on-error: true # Failing to estimate SCI doesn't mean a test failure.

      - name: Use Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Eco CI Energy Estimation - Get Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v5
        with:
          task: get-measurement
          label: "setup-python"
        continue-on-error: true

      - name: Install tooling for managing dependencies
        shell: bash
        run: |
          python -m pip install --upgrade uv wheel

      - name: Eco CI Energy Estimation - Get Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v5
        with:
          task: get-measurement
          label: "pip install uv wheel"
        continue-on-error: true

      - name: Install dependencies
        shell: bash
        run: |
          uv venv
          uv sync --locked

      - name: Eco CI Energy Estimation - Get Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v5
        with:
          task: get-measurement
          label: "pip install requirements"
        continue-on-error: true

