from .common import *  # noqa

# Minimal settings for ORM/library usage
# Keeps all apps but removes dev-specific middleware for faster setup

INTERNAL_IPS = ["127.0.0.1"]
ALLOWED_HOSTS.extend(["127.0.0.1", "localhost"])  # noqa

# Remove dev-only apps that may not be installed when used as a library
INSTALLED_APPS = [
    app for app in INSTALLED_APPS
    if app not in [
        "debug_toolbar",
        "django_browser_reload",
        "whitenoise.runserver_nostatic",
    ]
]

# Remove middleware that requires dev-only apps, request/response cycles,
# or external services that are not available in a library environment
MIDDLEWARE = [
    mw for mw in MIDDLEWARE
    if mw not in [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",
        'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',
        "basicauth.middleware.BasicAuthMiddleware",
    ]
]

# http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_MANIFEST_STRICT
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# override settings, so we don't need to run rabbitmq when using as library
# For more, see https://github.com/Bogdanp/django_dramatiq#testing
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.stub.StubBroker",
    "OPTIONS": {},
    "MIDDLEWARE": [
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
    ],
}

# Use dummy caches for library usage
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    },
    "file_resubmit": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    },
}

# Fix deprecated django-guardian setting
GUARDIAN_MONKEY_PATCH_USER = False
# Remove deprecated GUARDIAN_MONKEY_PATCH if it exists
globals().pop("GUARDIAN_MONKEY_PATCH", None)

# Disable drf api logger for library usage
DRF_LOGGER_INTERVAL = 1

# we replace this with the autogenerated address for a specific trello board in production
TRELLO_REGISTRATION_EMAIL_TO_BOARD_ADDRESS = "mail-to-board@localhost"
