# Generated by Django 2.2.6 on 2019-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greencheckasn',
            name='asn',
            field=models.IntegerField(verbose_name='Autonomous system number'),
        ),
        migrations.AlterField(
            model_name='greenchecktld',
            name='hps',
            field=models.IntegerField(verbose_name='Hostingproviders registered in tld'),
        ),
    ]
