# Generated by Django 2.2.6 on 2019-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0002_auto_20191031_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greencheckasnapprove',
            name='action',
            field=models.TextField(choices=[('', 'empty'), ('new', 'new'), ('update', 'update')]),
        ),
        migrations.AlterField(
            model_name='greencheckipapprove',
            name='action',
            field=models.TextField(choices=[('', 'empty'), ('new', 'new'), ('update', 'update')]),
        ),
        migrations.AlterField(
            model_name='greencheckasnapprove',
            name='status',
            field=models.TextField(choices=[('Approved', 'approved'), ('Deleted', 'deleted'), ('New', 'new'), ('Removed', 'removed'), ('Update', 'update')]),
        ),
        migrations.AlterField(
            model_name='greencheckipapprove',
            name='status',
            field=models.TextField(choices=[('Approved', 'approved'), ('Deleted', 'deleted'), ('New', 'new'), ('Removed', 'removed'), ('Update', 'update')]),
        ),
    ]
