# Generated by Django 2.2.6 on 2019-11-01 15:34

import apps.greencheck.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0002_approval_original_id_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greencheck',
            name='ip',
            field=apps.greencheck.models.IpAddressField(max_length=39),
        ),
        migrations.AlterField(
            model_name='greencheckip',
            name='ip_end',
            field=apps.greencheck.models.IpAddressField(db_column='ip_eind', max_length=39),
        ),
        migrations.AlterField(
            model_name='greencheckip',
            name='ip_start',
            field=apps.greencheck.models.IpAddressField(max_length=39),
        ),
        migrations.AlterField(
            model_name='greencheckipapprove',
            name='ip_end',
            field=apps.greencheck.models.IpAddressField(db_column='ip_eind', max_length=39),
        ),
        migrations.AlterField(
            model_name='greencheckipapprove',
            name='ip_start',
            field=apps.greencheck.models.IpAddressField(max_length=39),
        ),
    ]
