# Generated by Django 2.2.17 on 2021-01-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0006_auto_20210120_0751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greencheck", name="greencheck_ip", field=models.IntegerField(),
        ),
    ]
