# Generated by Django 2.2.17 on 2021-01-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0008_auto_20210120_0916'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='greencheck',
            name='date',
            field=models.DateTimeField(db_column='datum'),
        ),
    ]
