# Generated by Django 2.2.17 on 2021-01-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0010_auto_20210120_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greencheck',
            name='hostingprovider',
            field=models.ForeignKey(blank=True, db_column='id_hp', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Hostingprovider'),
        )
    ]
