# Generated by Django 2.2.18 on 2021-02-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0012_auto_20210120_1433'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='greendomain',
            table='greendomain',
        ),
    ]
