# Generated by Django 2.2.19 on 2021-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0013_auto_20210215_1809"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="greencheckasn",
            constraint=models.UniqueConstraint(
                fields=("asn", "active"), name="unique_active_asns"
            ),
        ),
    ]
