# Generated by Django 2.2.18 on 2021-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0013_auto_20210215_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greencheckasn',
            name='asn',
            field=models.IntegerField(unique=True, verbose_name='Autonomous system number'),
        ),
    ]
