# Generated by Django 2.2.19 on 2021-03-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0014_auto_20210314_1704"),
    ]

    operations = [
        migrations.AlterModelTable(name="greencheck", table="greencheck_2021",),
    ]
