# Generated by Django 3.2 on 2021-04-30 09:41

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0017_auto_20210429_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreencheckStats',
        ),
        migrations.AddField(
            model_name='dailystat',
            name='green',
            field=django_mysql.models.EnumField(choices=[('yes', 'Yes'), ('no', 'No'), ('old', 'Old')], default='no'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 9, 41, 36, 750763), verbose_name='Date for stats'),
        ),
        migrations.AlterField(
            model_name='greencheck',
            name='green',
            field=django_mysql.models.EnumField(choices=[('yes', 'Yes'), ('no', 'No'), ('old', 'Old')]),
        ),
        migrations.AlterField(
            model_name='greencheck',
            name='type',
            field=django_mysql.models.EnumField(choices=[('as', 'as'), ('ip', 'ip'), ('none', 'none'), ('url', 'url'), ('whois', 'whois')], default='none'),
        ),
    ]
