# Generated by Django 3.2.13 on 2022-05-15 18:35

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0018_auto_20210917_1012"),
    ]

    operations = [
        migrations.CreateModel(
            name="CO2Intensity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generation_from_fossil", models.FloatField(default=0)),
                ("country_name", models.CharField(max_length=255)),
                (
                    "country_code_iso_2",
                    models.CharField(max_length=255, blank=True, null=True),
                ),
                ("country_code_iso_3", models.CharField(max_length=255)),
                ("carbon_intensity", models.FloatField(default=0)),
                ("carbon_intensity_type", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
            ],
        )
    ]
