# Generated by Django 3.2.13 on 2022-05-15 18:38

from django.db import migrations


def add_ember_data(apps, schema_editor):
    """
    Add the data from Ember to allow matching
    of the IP address to the CO2 intensity data

    """
    CO2Intensity = apps.get_model("greencheck", "CO2Intensity")

    # load the CSV of data with info from 2021 and 2020

    # for each country
    # add a co2 reading, and the kind (avg), and the percentage fossil generation
    # make sure there is the 2 and 3 letter iso code
    # add the year


def clear_ember_data(apps, schema_editor):
    """
    Clear ember data.

    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0019_auto_20220515_1835"),
    ]

    operations = []

