# Generated by Django 3.2.16 on 2023-01-24 11:22

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0019_auto_20220515_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreencheckStats',
        ),
        migrations.DeleteModel(
            name='GreencheckStatsTotal',
        ),
        migrations.DeleteModel(
            name='GreencheckWeeklyStats',
        ),
        migrations.AlterField(
            model_name='co2intensity',
            name='carbon_intensity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 11, 22, 44, 664678), verbose_name='Date for stats'),
        ),
        migrations.AlterField(
            model_name='greencheck',
            name='green',
            field=django_mysql.models.EnumField(choices=[('yes', 'Yes'), ('no', 'No'), ('old', 'Old')]),
        ),
        migrations.AlterField(
            model_name='greencheck',
            name='type',
            field=django_mysql.models.EnumField(choices=[('url', 'url'), ('whois', 'whois'), ('ip', 'ip'), ('none', 'none'), ('as', 'as'), ('carbontxt', 'carbon.txt')], default='none'),
        ),
        migrations.AlterField(
            model_name='greencheckasnapprove',
            name='action',
            field=models.TextField(choices=[('empty', 'empty'), ('new', 'new'), ('update', 'update'), ('none', 'none')]),
        ),
        migrations.AlterField(
            model_name='greencheckipapprove',
            name='action',
            field=models.TextField(choices=[('empty', 'empty'), ('new', 'new'), ('update', 'update'), ('none', 'none')]),
        ),
        migrations.AlterField(
            model_name='greenlist',
            name='type',
            field=django_mysql.models.EnumField(choices=[('empty', 'empty'), ('new', 'new'), ('update', 'update'), ('none', 'none')]),
        ),
    ]
