# Generated by Django 5.0.9 on 2025-06-12 16:59

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0020_auto_20240223_2122"),
    ]

    operations = [
        migrations.AddField(
            model_name="greendomain",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql="UPDATE greendomain SET created=modified",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='greendomain',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
