# Generated by Django 3.2 on 2021-05-03 12:42

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0021_auto_20210430_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreencheckStatsTotal',
        ),
        migrations.DeleteModel(
            name='GreencheckWeeklyStats',
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='green',
            field=django_mysql.models.EnumField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')]),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 12, 42, 28, 330918), verbose_name='Date for stats'),
        ),
        migrations.AlterField(
            model_name='greencheck',
            name='type',
            field=django_mysql.models.EnumField(choices=[('empty', 'empty'), ('new', 'new'), ('update', 'update'), ('none', 'none')], default='none'),
        ),
        migrations.AlterField(
            model_name='greencheckasnapprove',
            name='action',
            field=models.TextField(choices=[('empty', 'empty'), ('new', 'new'), ('update', 'update'), ('none', 'none')]),
        ),
        migrations.AlterField(
            model_name='greencheckipapprove',
            name='action',
            field=models.TextField(choices=[('empty', 'empty'), ('new', 'new'), ('update', 'update'), ('none', 'none')]),
        ),
        migrations.AlterField(
            model_name='greenlist',
            name='type',
            field=django_mysql.models.EnumField(choices=[('empty', 'empty'), ('new', 'new'), ('update', 'update'), ('none', 'none')]),
        ),
    ]
