# Generated by Django 5.0.9 on 2025-07-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0022_delete_dailystat_delete_greencheckstats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="greendomain",
            name="listed_provider",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.RunSQL(
            """
            UPDATE greendomain
            LEFT OUTER JOIN hostingproviders
            ON greendomain.hosted_by_id = hostingproviders.id
            SET greendomain.listed_provider = COALESCE(hostingproviders.is_listed, 0)
            """
        )
    ]
