# Generated by Django 3.2 on 2021-05-03 12:44

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0022_auto_20210503_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystat',
            name='green',
            field=django_mysql.models.EnumField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 12, 44, 37, 793832), verbose_name='Date for stats'),
        ),
    ]
