# Generated by Django 3.2 on 2021-05-03 15:02

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0023_auto_20210503_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 15, 2, 57, 945674), verbose_name='Date for stats'),
        ),
    ]
