# Generated by Django 3.2 on 2021-05-11 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencheck', '0025_auto_20210511_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystat',
            name='stat_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 10, 12, 51, 21, 906382), verbose_name='Date for stats'),
        ),
    ]
