# Generated by Django 5.0.9 on 2025-12-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0028_delete_greenchecktld"),
    ]

    operations = [
        migrations.AddField(
            model_name="greendomainbadge",
            name="legacy",
            field=models.BooleanField(default=False),
        ),
    ]
