# Generated by Django 5.2.9 on 2025-12-31 07:51

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0029_greendomainbadge_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="greendomainbadge",
            name="pk",
            field=models.CompositePrimaryKey(
                "domain",
                "legacy",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="greendomainbadge",
            name="domain",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[apps.accounts.validators.DomainNameValidator],
            ),
        ),
    ]
