# Generated by Django 5.2.9 on 2025-12-31 07:52

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greencheck", "0030_greendomainbadge_pk_alter_greendomainbadge_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greendomainbadge",
            name="domain",
            field=models.CharField(
                max_length=255,
                validators=[apps.accounts.validators.DomainNameValidator],
            ),
        ),
    ]
