services:
  main:
    # we use the default codespaces image. this likely requires an x86
    # processor, so might not work on arm machines
    image: "mcr.microsoft.com/devcontainers/universal:2"
  
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000

  # we map host ports to higher numbers than usual because we do not know
  # what ports are already in use on the host machine. 
  # If a user already uses MySQL, or RabbitMQ, then the codespace 
  # can fail in difficult to debug ways.
  # For more, see this
  # https://containers.dev/guide/dockerfile#docker-compose
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=deploy
      - MYSQL_DATABASE=greencheck
      - MYSQL_USER=deploy
      - MYSQL_PASSWORD=deploy
    ports:
      - "13306:3306"  # Map container port 3306 to host port 13306
  rabbitmq:
    image: rabbitmq:3.11
    restart: unless-stopped
    ports:
      - "15672:5672"  # Map container port 5672 to host port 15672
