services:
  main:
    # we use the default codespaces image. this likely requires an x86
    # processor, so might not work on arm machines
    image: "mcr.microsoft.com/devcontainers/universal:2"
  
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "8000:8000"
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=deploy
      - MYSQL_DATABASE=greencheck
      - MYSQL_USER=deploy
      - MYSQL_PASSWORD=deploy
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3.11
    restart: unless-stopped
    ports:
      - "5672:5672"
