# Generated by Django 2.2.19 on 2021-03-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_auto_20210201_2230"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostingProviderSupportingDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.FileField(blank=True, upload_to="uploads/")),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "hostingprovider",
                    models.ForeignKey(
                        db_column="id_hp",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostingprovider_evidence",
                        to="accounts.Hostingprovider",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="DatacentreSupportingDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.FileField(blank=True, upload_to="uploads/")),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "datacenter",
                    models.ForeignKey(
                        db_column="id_dc",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datacenter_evidence",
                        to="accounts.Datacenter",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
