# Generated by Django 3.2 on 2021-08-09 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210708_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category', models.CharField(help_text='A category for this kind of message. For internal use', max_length=255)),
                ('subject', models.CharField(help_text='The default subject of the email message. This is what the user sees in their inbox', max_length=255)),
                ('body', models.CharField(help_text='The default content of the message sent to the user. Supports markdown.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='hostingprovidersupportingdocument',
            name='hostingprovider',
            field=models.ForeignKey(db_column='id_hp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='accounts.hostingprovider'),
        ),
    ]
