# Generated by Django 3.2 on 2021-08-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210809_1525'),
    ]

    operations = [
    ]
