# Generated by Django 3.2 on 2021-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_starting_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='body',
            field=models.TextField(help_text='The default content of the message sent to the user. Supports markdown.', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='subject',
            field=models.CharField(help_text='The default subject of the email message. This is whatthe user sees in their inbox', max_length=255),
        ),
    ]
