# Generated by Django 3.2 on 2021-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210809_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='body',
            field=models.TextField(help_text='The default content of the message sent to the user. Supports markdown.'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='subject',
            field=models.CharField(help_text='The default subject of the email message. This is what the user sees in their inbox', max_length=255),
        ),
    ]
