# Generated by Django 3.2 on 2021-08-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210809_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingcommunication',
            name='message_content',
            field=models.TextField(blank=True),
        ),
    ]
