# Generated by Django 3.2.13 on 2022-07-08 12:37

from django.db import migrations
from ..group_permissions import populate_group_permissions


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_label_slug"),
    ]

    operations = [migrations.RunPython(populate_group_permissions)]
