# Generated by Django 3.2.13 on 2022-07-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20220708_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hostingprovider',
            field=models.ForeignKey(blank=True, db_column='id_hp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hostingprovider'),
        ),
    ]
