# Generated by Django 3.2.14 on 2022-07-11 08:48

from django.db import migrations
from ..group_permissions import populate_group_permissions


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_alter_user_hostingprovider"),
    ]

    operations = [migrations.RunPython(populate_group_permissions)]
