# Generated by Django 3.2.15 on 2022-08-04 15:02

from django.db import migrations
from ..group_permissions import populate_group_permissions_2022_08_05


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_auto_20220711_0848"),
    ]

    operations = [migrations.RunPython(populate_group_permissions_2022_08_05)]
