# Generated by Django 3.2.16 on 2022-11-25 16:01

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


def forward_func(apps, schema_editor):
    """
    Migrate existing data to allow "request" field to be non-nullable
    """
    db_alias = schema_editor.connection.alias

    # copy location.request to asn.request
    ProviderRequestASN = apps.get_model("accounts", "ProviderRequestASN")
    for asn in ProviderRequestASN.objects.using(db_alias).iterator():
        asn.request = asn.location.request

    # copy location.request to iprange.request
    ProviderRequestIPRange = apps.get_model("accounts", "ProviderRequestIPRange")
    for ip in ProviderRequestIPRange.objects.using(db_alias).iterator():
        ip.request = ip.location.request

    # copy location.request to evidence.request
    ProviderRequestEvidence = apps.get_model("accounts", "ProviderRequestEvidence")
    for evidence in ProviderRequestEvidence.objects.using(db_alias).iterator():
        evidence.request = evidence.location.request


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("accounts", "0033_remove_providerrequestsupplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrequest",
            name="services",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Click the services that your organisation offers. These will be listed in the green web directory.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Services offered",
            ),
        ),
        migrations.AddField(
            model_name="providerrequestasn",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.providerrequest",
            ),
        ),
        migrations.AddField(
            model_name="providerrequestevidence",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.providerrequest",
            ),
        ),
        migrations.AddField(
            model_name="providerrequestiprange",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.providerrequest",
            ),
        ),
        migrations.RunPython(code=forward_func),
        migrations.RemoveField(
            model_name="providerrequestasn",
            name="location",
        ),
        migrations.RemoveField(
            model_name="providerrequestevidence",
            name="location",
        ),
        migrations.RemoveField(
            model_name="providerrequestiprange",
            name="location",
        ),
        migrations.RemoveField(
            model_name="providerrequestlocation",
            name="services",
        ),
        migrations.AlterField(
            model_name='providerrequestasn',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.providerrequest'),
        ),
        migrations.AlterField(
            model_name='providerrequestevidence',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.providerrequest'),
        ),
        migrations.AlterField(
            model_name='providerrequestiprange',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.providerrequest'),
        ),
    ]
