# Generated by Django 3.2.16 on 2023-01-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_authorised_by_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRequestConsent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("newsletter_opt_in", models.BooleanField(default=False)),
                ("data_processing_opt_in", models.BooleanField(default=False)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.providerrequest",
                    ),
                ),
            ],
        ),
    ]
