# Generated by Django 3.2.18 on 2023-02-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0039_hostingprovider_city_squashed_0041_remove_providerrequestlocation_description",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datacentersupportingdocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("Annual report", "Annual Report"),
                    ("Web page", "Web Page"),
                    ("Certificate", "Certificate"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hostingprovider",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hostingprovider",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.providerrequest",
            ),
        ),
        migrations.AddField(
            model_name="hostingprovidersupportingdocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("Annual report", "Annual Report"),
                    ("Web page", "Web Page"),
                    ("Certificate", "Certificate"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
