# Generated by Django 3.2.18 on 2023-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0040_hostingprovider_providerrequest_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending review", "Pending Review"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Open", "Open"),
                ],
                max_length=255,
            ),
        ),
    ]
