# Generated by Django 3.2.16 on 2023-01-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_auto_20230124_1123"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerrequestlocation",
            name="description",
        ),
    ]
