# Generated by Django 3.2.18 on 2023-02-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0043_providerrequest_location_import_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerrequestevidence",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
