# Generated by Django 3.2.18 on 2023-05-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_provider_request_approved_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostingprovider',
            old_name='services',
            new_name='service_tags',
        ),
    ]
