# Generated by Django 3.2.18 on 2023-05-07 21:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_rename_services_hostingprovider_service_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hostingprovider')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_providerservice_items', to='accounts.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hostingprovider',
            name='services',
            field=taggit.managers.TaggableManager(blank=True, help_text='Click the services that your organisation offers. These will be listed in the green web directory.', through='accounts.ProviderService', to='accounts.Service', verbose_name='Services Offered'),
        ),
    ]
