# Generated by Django 3.2.18 on 2023-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0052_merge_20230510_1057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending review", "Pending Review"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Open", "Open"),
                    ("Removed", "Removed"),
                ],
                max_length=255,
            ),
        ),
    ]
