# Generated by Django 3.2.18 on 2023-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0053_alter_providerrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrequest",
            name="network_import_required",
            field=models.BooleanField(default=False),
        ),
    ]
