# Generated by Django 3.2.19 on 2023-05-31 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0056_populate_existing_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="hostingprovider",
        ),
    ]
