# Generated by Django 3.2.19 on 2023-07-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_providerrequest_missing_network_explanation'),
        ('accounts', '0057_remove_user_hostingprovider_fk'),
    ]

    operations = [
    ]
