# Generated by Django 3.2.20 on 2023-07-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_user_is_staff'),
        ('accounts', '0058_merge_20230712_1143'),
    ]

    operations = [
    ]
