# Generated by Django 3.2.21 on 2023-09-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_merge_20230712_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingprovider',
            name='website',
            field=models.URLField(max_length=255),
        ),
    ]
