# Generated by Django 3.2.21 on 2023-09-21 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0060_alter_hostingprovider_website"),
        ("accounts", "0061_providerrequest_rename_open_status"),
    ]

    operations = []
