# Generated by Django 3.2.21 on 2023-09-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0062_merge_20230921_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrequest",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.hostingprovider",
            ),
        ),
    ]
