# Generated by Django 5.0.9 on 2025-05-29 10:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_create_providerverificationbasis"),
    ]

    operations = [
        migrations.RenameModel("DomainHash", "LinkedDomain"),
        migrations.RemoveField(
            model_name='LinkedDomain',
            name='hash',
        ),
    ]
