# Generated by Django 5.0.9 on 2025-05-30 09:31

import apps.accounts.validators
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0073_add_primary_field_to-linkedomain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkeddomain",
            name="domain",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[apps.accounts.validators.DomainNameValidator()],
            ),
        ),
    ]
