# Generated by Django 5.0.9 on 2025-05-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0074_alter_linkeddomain_options"),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO accounts_linkeddomain
                    (created, modified, domain, created_by_id, provider_id, state, `primary`)
                SELECT
                    NOW() AS created,
                    NOW() AS modified,
                    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(carbon_txt_url, '/', 3), '://', -1), '/', 1), '?', 1) as domain,
                    NULL AS created_by_id,
                    id AS provider_id,
                    "Approved" AS state,
                    TRUE AS `primary`
                FROM hostingproviders
                WHERE carbon_txt_url IS NOT NULL;
            """
        ),
        migrations.RemoveField(
            model_name='Hostingprovider',
            name='carbon_txt_url',
        ),
    ]
