# Generated by Django 5.0.9 on 2025-06-03 13:25

from django.db import migrations

from ..group_permissions import group_permissions_2025_06_03_add_linked_domain_permissions_for_admins

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0075_migrate_old_carbon_txt_implementations"),
    ]

    operations = [
        migrations.RunPython(
            group_permissions_2025_06_03_add_linked_domain_permissions_for_admins
        )
    ]
