# Generated by Django 5.0.9 on 2025-06-05 10:45

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0076_linked_domain_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkeddomain",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
