# Generated by Django 5.0.9 on 2025-09-05 09:51

import apps.accounts.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0085_alter_providercarbontxt_carbon_txt_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonTxtDomainResultCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[apps.accounts.validators.DomainNameValidator],
                    ),
                ),
                (
                    "carbon_txt_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.providercarbontxt",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
