# Generated by Django 5.0.9 on 2025-09-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0086_carbontxtdomainresultcache"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carbontxtdomainresultcache",
            old_name="carbon_txt_id",
            new_name="carbon_txt",
        ),
    ]
