# Generated by Django 5.2.9 on 2026-05-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0093_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_access_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="api_access_motivation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="override_api_key_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
