# Generated by Django 5.2.9 on 2026-05-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0094_user_api_access_banned_user_api_access_motivation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKeyPrivilegeLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="apikey",
            name="privilege_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.apikeyprivilegelevel",
            ),
        ),
    ]
