# Generated by Django 5.2.9 on 2026-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0099_apikey_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiservice",
            name="documentation_url",
            field=models.URLField(
                default="https://developers.thegreenwebfoundation.org"
            ),
            preserve_default=False,
        ),
    ]
