# Generated by Django 5.2.9 on 2026-06-28 16:47

from django.db import migrations, models


def backfill_version_to_june_2026(apps, schema_editor):
    """
    All pre-existing VerificationBasis records predate the October 2026
    criteria, so they are backfilled to the June 2026 version. The AddField
    operation above seeds every row with the model default ("2026-10"); this
    step overrides that for pre-existing rows. New admin-created records
    pick up the model default (October 2026) going forward.
    """
    VerificationBasis = apps.get_model("accounts", "VerificationBasis")
    VerificationBasis.objects.all().update(version="2026-06")


def unbackfill_version(apps, schema_editor):
    # reverse: reset to the model default so re-applying repopulates correctly
    VerificationBasis = apps.get_model("accounts", "VerificationBasis")
    VerificationBasis.objects.all().update(version="2026-10")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0102_apikeyprivilegelevel_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationbasis",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Supporting description for given basis for verification. "
                    "Used in end-user facing UI to help explain what a given basis means"
                ),
            ),
        ),
        migrations.AddField(
            model_name="verificationbasis",
            name="version",
            field=models.CharField(
                choices=[
                    ("2026-06", "Current (June 2026)"),
                    ("2026-10", "Upcoming (October 2026)"),
                ],
                default="2026-10",
                help_text="Which version of the verification criteria this basis belongs to. New admin-created records target the October 2026 regime by default.",
                max_length=128,
            ),
        ),
        migrations.RunPython(
            backfill_version_to_june_2026,
            reverse_code=unbackfill_version,
        ),
    ]
