# Generated by Django 5.2.9 on 2026-07-11 06:42

from django.db import migrations

def create_verification_basis_v2_claimed_percentage_flag(apps, schema_editor):
    """
    Create the verification_basis_v2_claimed_percentage waffle flag.
    """
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.get_or_create(
        name="verification_basis_v2_claimed_percentage",
        defaults={
            "everyone": None,
            "superusers": False,
            "staff": False,
            "authenticated": False,
            "note": (
                "Controls visibility of in the provider request evidence step where "
                " ask for percentage share for each disclosure."
            ),
        },
    )


def remove_verification_basis_v2_claimed_percentage_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.filter(name="verification_basis_v2_claimed_percentage").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0108_merge_20260711_0602"),
    ]

    operations = [
        migrations.RunPython(
            create_verification_basis_v2_claimed_percentage_flag,
            reverse_code=remove_verification_basis_v2_claimed_percentage_flag
        )
    ]
