# Generated by Django 5.2.9 on 2026-08-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0110_upstream_provider_through_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="upstreamprovider",
            options={
                "verbose_name": "upstream provider",
                "verbose_name_plural": "upstream providers",
            },
        ),
    ]
