# Generated by Django 5.2.9 on 2026-08-14 15:17

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0113_create_upstream_providers_directory_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostingProviderLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "hostingprovider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="accounts.hostingprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "hosting provider location",
                "verbose_name_plural": "hosting provider locations",
            },
        ),
        migrations.CreateModel(
            name="HostingProviderSupportingDocumentLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_links",
                        to="accounts.hostingprovidersupportingdocument",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="accounts.hostingproviderlocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "disclosure region",
                "verbose_name_plural": "disclosure regions",
                "unique_together": {("document", "location")},
            },
        ),
        migrations.AddField(
            model_name="hostingprovidersupportingdocument",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="supporting_documents",
                through="accounts.HostingProviderSupportingDocumentLocation",
                to="accounts.hostingproviderlocation",
            ),
        ),
        migrations.CreateModel(
            name="ProviderRequestEvidenceLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_links",
                        to="accounts.providerrequestevidence",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="accounts.providerrequestlocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidence region",
                "verbose_name_plural": "evidence regions",
                "unique_together": {("evidence", "location")},
            },
        ),
        migrations.AddField(
            model_name="providerrequestevidence",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="evidence",
                through="accounts.ProviderRequestEvidenceLocation",
                to="accounts.providerrequestlocation",
            ),
        ),
    ]
