# Generated by Django 5.2.9 on 2026-08-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0116_create_link_disclosures_to_regions_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisclosureClaim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "organisation_basis",
                                "Organisation basis for verification",
                            ),
                            (
                                "third_party_assurance",
                                "Third-party independent assurance",
                            ),
                            ("needs_help", "I'd like help confirming this"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2026-06", "Current (June 2026)"),
                            ("2026-10", "Upcoming (October 2026)"),
                        ],
                        help_text="For ORGANISATION_BASIS claims, which verification-basis version this tracks. Null for version-agnostic claims.",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "basis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for ORGANISATION_BASIS claims; links to the VerificationBasis this claim represents.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disclosure_claims",
                        to="accounts.verificationbasis",
                    ),
                ),
            ],
            options={
                "verbose_name": "disclosure claim",
                "verbose_name_plural": "disclosure claims",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="HostingProviderSupportingDocumentClaim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links_live",
                        to="accounts.disclosureclaim",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_links",
                        to="accounts.hostingprovidersupportingdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "disclosure claim",
                "verbose_name_plural": "disclosure claims",
                "unique_together": {("document", "claim")},
            },
        ),
        migrations.AddField(
            model_name="hostingprovidersupportingdocument",
            name="claims",
            field=models.ManyToManyField(
                blank=True,
                related_name="supporting_documents",
                through="accounts.HostingProviderSupportingDocumentClaim",
                to="accounts.disclosureclaim",
            ),
        ),
        migrations.CreateModel(
            name="ProviderRequestEvidenceClaim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links_draft",
                        to="accounts.disclosureclaim",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_links",
                        to="accounts.providerrequestevidence",
                    ),
                ),
            ],
            options={
                "verbose_name": "disclosure claim",
                "verbose_name_plural": "disclosure claims",
                "unique_together": {("evidence", "claim")},
            },
        ),
        migrations.AddField(
            model_name="providerrequestevidence",
            name="claims",
            field=models.ManyToManyField(
                blank=True,
                related_name="evidence_draft",
                through="accounts.ProviderRequestEvidenceClaim",
                to="accounts.disclosureclaim",
            ),
        ),
    ]
