---
- name: Set up a virtual environment for this project
  ansible.builtin.command: /home/deploy/.local/bin/uv venv
  args:
    chdir: "{{ project_root }}/current"
  changed_when: false
  tags: [uv]

- name: Install python dependencies with uv
  ansible.builtin.shell: /home/deploy/.local/bin/uv sync --locked
  args:
    chdir: "{{ project_root }}/current"
    executable: "/usr/bin/bash"
  tags: [uv]

- name: Update node deps for building tailwind
  ansible.builtin.shell: |
    FNM_PATH="/home/deploy/.local/share/fnm"
    export PATH="$FNM_PATH:$PATH"
    eval "`fnm env`"
    /home/deploy/.local/bin/uv run dotenv run ./manage.py tailwind update
  args:
    chdir: "{{ project_root }}/current"
    executable: "/usr/bin/bash"
  when: update_front_end_deps is true
  tags: [uv]

- name: Install node deps for building tailwind
  ansible.builtin.shell: |
    FNM_PATH="/home/deploy/.local/share/fnm"
    export PATH="$FNM_PATH:$PATH"
    eval "`fnm env`"
    /home/deploy/.local/bin/uv run dotenv run ./manage.py tailwind install
  args:
    executable: "/usr/bin/bash"
    chdir: "{{ project_root }}/current"
  changed_when: false
  tags: [uv]
